### ISSUE TITLE
E/SQLiteLog: (283) recovered 164 frames from WAL file 

### ISSUE THREAD

**Issue by yokei15** [couchbaselabs/couchbase-lite-tutorial-android#4]
Hi,
Am facing this type of error,
E/SQLiteLog: (283) recovered 164 frames from WAL file /data/data/com.example.android/files/couchbaseevents.cblite2/db.sqlite3-wal

**Comment by snej** [comment]
Please file this against couchbase-lite-java-core.

**Comment by castasat** [comment]
Here is an example how I close database in my application to extinguish this error message: https://stackoverflow.com/questions/53124390/e-sqlitelog-283-recovered-frames-from-wal-file/56361114#56361114
